#!/usr/bin/env node
/**
 * 构建前写入仓库根 `.env.deploy.local`（已 gitignore），供各应用 Vite 读取并注入 `import.meta.env.VITE_DEPLOY_TAG`。
 *
 * 环境变量（可选）：
 *   DEPLOY_SCOPE — 与 CI / workflow 一致：all | 子应用目录名；未设时兜底 local
 *   BUILD_BRANCH — 显示在 tag 文案中；未设时尝试 `git branch --show-current`
 *
 * 校验：DEPLOY_SCOPE 为子应用名时须存在 apps/<name>/package.json（与 workflow 下拉一致；非法则 exit 1）
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { listWorkspaceAppNames } from './repo_apps.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '../..');
const outfile = path.join(root, '.env.deploy.local');

const PRESETS = {
  main: { emoji: '🎉', title: '主应用' },
  login: { emoji: '🔐', title: '登录子应用' },
  blog: { emoji: '📝', title: 'Blog' },
  agent: { emoji: '🤖', title: 'AI Agent' },
  skill: { emoji: '📊', title: '技能' },
  resume: { emoji: '📄', title: '简历' },
};

function formatShanghaiTime() {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: 'Asia/Shanghai',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hourCycle: 'h23',
  }).formatToParts(new Date());
  const get = (t) => parts.find((p) => p.type === t)?.value ?? '';
  return `${get('year')}-${get('month')}-${get('day')} ${get('hour')}:${get('minute')}:${get('second')}`;
}

function gitBranch() {
  try {
    return execSync('git branch --show-current', { cwd: root, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

const scopeRaw = (process.env.DEPLOY_SCOPE ?? '').trim();
const scope = scopeRaw || 'local';
let branch = (process.env.BUILD_BRANCH ?? '').trim();
if (!branch) branch = gitBranch();

if (scope !== 'all' && scope !== 'local') {
  const apps = listWorkspaceAppNames();
  if (!apps.includes(scope)) {
    console.error(`❌ 无效的 DEPLOY_SCOPE: "${scope}"，应为 all、local 或以下之一: ${apps.join(', ')}`);
    process.exit(1);
  }
}

let label;
if (scope === 'all') label = { emoji: '📦', title: '全量构建' };
else if (scope === 'local') label = { emoji: '🔧', title: '本地构建' };
else label = PRESETS[scope] ?? { emoji: '✅', title: `子应用 ${scope}` };

const time = formatShanghaiTime();
const parts = [`${label.emoji} ${label.title}`, time];
if (branch) parts.push(`分支 ${branch}`);
if (scope && scope !== 'local') parts.push(`范围 ${scope}`);
const tag = parts.join(' · ');

const lines = [
  '# Generated by scripts/deploy/emit_deploy_tag_env.mjs — do not commit',
  `VITE_DEPLOY_TAG=${JSON.stringify(tag)}`,
  '',
];
fs.writeFileSync(outfile, lines.join('\n'), 'utf8');
console.log(`✅ ${path.relative(root, outfile)} ← VITE_DEPLOY_TAG`);
