import fs from 'node:fs';
import path from 'node:path';

export function toPascal(s) {
  return String(s)
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/g)
    .filter(Boolean)
    .map((w) => w.slice(0, 1).toUpperCase() + w.slice(1))
    .join('');
}

export function patchGeneratedClientGen({ clientGenPath }) {
  let s = fs.readFileSync(clientGenPath, 'utf8');
  s = s.replace(/import \{ openApiHttpClient \} from '\.\.\/openapi-http';?\r?\n?/, '');
  s = s.replace(/import \{ openApiHttpClient \} from "\.\.\/openapi-http";?\r?\n?/, '');
  if (!s.includes("from './openapi-http.gen.js'")) {
    s = s.replace(
      "import type { ClientOptions as ClientOptions2 } from './types.gen.js';",
      "import type { ClientOptions as ClientOptions2 } from './types.gen.js';\nimport { openApiHttpClient } from './openapi-http.gen.js';",
    );
  }
  if (!s.includes('axios: openApiHttpClient')) {
    s = s.replace(
      /createConfig(?:<[^>]*>)?\(\{\s*baseURL:/,
      'createConfig<ClientOptions2>({ axios: openApiHttpClient, baseURL:',
    );
  }
  /* 无 servers 时 Hey API 可能生成 createConfig<...>()，需单独注入 axios */
  if (!s.includes('axios: openApiHttpClient')) {
    s = s.replace(
      /createClient\(createConfig(?:<[^>]*>)?\(\s*\)\)/,
      'createClient(createConfig<ClientOptions2>({ axios: openApiHttpClient }))',
    );
  }
  fs.writeFileSync(clientGenPath, s);
}

export function writeGenWrappers({ genRoot, name, outRel }) {
  const pascal = toPascal(name);
  const genDir = path.join(genRoot, outRel);
  const indexPath = path.join(genDir, 'index.ts');
  const typesPath = path.join(genDir, 'types.ts');
  const fnName = `OpenApi${pascal}Fn`;
  const initTypeName = `OpenApi${pascal}FnInit`;
  const resolveName = `resolveOpenApi${pascal}Base`;
  const cfgBaseName = `configureOpenApi${pascal}Base`;
  const cfgRtName = `configureOpenApi${pascal}ResponseType`;

  fs.writeFileSync(typesPath, `/** ${name} 文档生成的类型。 */\nexport type * from './types.gen';\n`, 'utf8');

  fs.writeFileSync(
    indexPath,
    `import type { ResponseType } from 'axios';\n` +
      `import { client } from './client.gen';\n` +
      `import * as sdk from './sdk.gen';\n` +
      `import {\n` +
      `  configureOpenApiErrorHandling,\n` +
      `  openApiSettings,\n` +
      `  type OpenApiAuthState,\n` +
      `  type OpenApiErrorHandlingOptions,\n` +
      `} from './openapi-http.gen';\n` +
      `import { createOpenApiInitializer, resolveBase, type OpenApiCommonInit } from '../../src/request';\n\n` +
      `export type { ResponseType };\n\n` +
      `export type ${initTypeName} = Partial<Pick<OpenApiAuthState, 'BASE' | 'WITH_CREDENTIALS'>> & {\n` +
      `  pathPrefix?: string;\n` +
      `  defaultResponseType?: ResponseType;\n` +
      `  token?: string | (() => string | Promise<string | undefined> | undefined);\n` +
      `  headers?: OpenApiAuthState['HEADERS'];\n` +
      `  errorHandling?: OpenApiErrorHandlingOptions;\n` +
      `};\n\n` +
      `export function ${resolveName}(init: Pick<${initTypeName}, 'BASE' | 'pathPrefix'>): string | undefined {\n` +
      `  return resolveBase(init);\n` +
      `}\n\n` +
      `export function ${cfgBaseName}(baseURL: string, more?: { responseType?: ResponseType }): void {\n` +
      `  openApiSettings.BASE = baseURL;\n` +
      `  client.setConfig({ baseURL, ...more });\n` +
      `}\n\n` +
      `export function ${cfgRtName}(responseType: ResponseType): void {\n` +
      `  client.setConfig({ responseType });\n` +
      `}\n\n` +
      `const init = createOpenApiInitializer({\n` +
      `  sdk,\n` +
      `  client,\n` +
      `  settings: openApiSettings,\n` +
      `  configureErrorHandling: configureOpenApiErrorHandling,\n` +
      `});\n\n` +
      `/** ${name}.yaml 对应的 SDK；在子应用入口初始化 BASE/token（该 spec 可能没有 servers.baseURL）。 */\n` +
      `export function ${fnName}(initArg?: ${initTypeName}): typeof sdk {\n` +
      `  return init(initArg as OpenApiCommonInit);\n` +
      `}\n\n` +
      `export {\n` +
      `  configureOpenApiErrorHandling,\n` +
      `  openApiHttpClient,\n` +
      `  openApiSilent,\n` +
      `  type OpenApiAuthState,\n` +
      `  type OpenApiErrorHandlingOptions,\n` +
      `  type OpenApiErrorReporter,\n` +
      `} from './openapi-http.gen';\n\n` +
      `export { client as client${pascal} } from './client.gen';\n` +
      `export * from './sdk.gen';\n` +
      `export type * from './types';\n`,
    'utf8',
  );
}

export function writeClientsBarrel({ genRoot, names }) {
  const outPath = path.join(genRoot, 'clients.ts');
  const lines = [
    `/**`,
    ` * AUTO-GENERATED by scripts/generate.mjs`,
    ` *`,
    ` * 目的：让 VSCode/TS 自动导入能直接提示来源于 '@packages/openapi'。`,
    ` * 注意：此文件每次 generate 会覆盖，请勿手改。`,
    ` */`,
    ``,
  ];

  for (const name of names) {
    const pascal = toPascal(name);
    const fn = `OpenApi${pascal}Fn`;
    const init = `OpenApi${pascal}FnInit`;
    const resolve = `resolveOpenApi${pascal}Base`;
    const cfgBase = `configureOpenApi${pascal}Base`;
    const cfgRt = `configureOpenApi${pascal}ResponseType`;

    // 只聚合“具名且不冲突”的初始化入口与其类型；不要聚合 sdk/types/runtime，避免跨 spec 命名冲突。
    lines.push(`export { ${fn}, ${resolve}, ${cfgBase}, ${cfgRt} } from './${name}-gen/index';`);
    lines.push(`export type { ${init} } from './${name}-gen/index';`);
    lines.push('');
  }

  lines.push('');
  fs.writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');
}
